// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AInput: typeof import('ant-design-vue/es')['Input']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    Box: typeof import('./src/components/box.vue')['default']
    BoxAnimate: typeof import('./src/components/boxAnimate.vue')['default']
    Colomn: typeof import('./src/components/colomn.vue')['default']
    EnemyOne: typeof import('./src/components/enemyOne.vue')['default']
    Minimap: typeof import('./src/components/minimap.vue')['default']
    Scroll: typeof import('./src/components/scroll.vue')['default']
  }
}
