// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BookOne: typeof import('./src/components/bookOne.vue')['default']
    BoxAnimate: typeof import('./src/components/boxAnimate.vue')['default']
    Scroll: typeof import('./src/components/scroll.vue')['default']
  }
}
