export { default as Book } from './book.vue';
export { default as BookDetail } from './bookDetail.vue';
export { default as Equipbox } from './equipbox.vue';
export { default as Fly } from './fly.vue';
export { default as Settings } from './settings.vue';
export { default as Shop } from './shop.vue';
export { default as Toolbox } from './toolbox.vue';
export { default as Hotkey } from './hotkey.vue';
export { default as Load } from './load.vue';
